spring:
    datasource:
        url: jdbc:mysql://localhost:1222/er-sols
        username: root
        password: password
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    main:
      banner-mode: "off"

urls:
  account-service: "localhost:8081"
management:
    endpoints:
        web:
            exposure:
                include: prometheus, health, info, httptrace

---
spring:
  profiles: docker-compose
  datasource:
      url: jdbc:mysql://vehicle-db:3306/vehicle-db
      username: root
      password: accounts
  jpa:
    show-sql: false
urls:
  account-service: "account-service:8080"

